name: Quick build
on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        description: 'Version number Eg: 4.2.0'

jobs:
  # build-linux:
  #   runs-on: ubuntu-20.04
  #   permissions:
  #     contents: write

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Configure
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y -f \
  #         libgtk-3-dev \
  #         libwebkit2gtk-4.0-37 \
  #         libwebkit2gtk-4.0-dev

  #     - name: Build
  #       run: ./scripts/bz.py

  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: linux_x64_binary
  #         path: bin/neutralino-linux_x64

  build-windows:
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python ./scripts/bz.py
        shell: cmd
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win_binary
          path: bin/neutralino-win_x64.exe

  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Download Linux build artifacts
      #   uses: actions/download-artifact@v4.1.7
      #   with:
      #     name: linux_x64_binary
      #     path: ./bin

      - name: Download Windows build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: win_binary
          path: ./bin

      - name: Create Release zip
        uses: vimtor/action-zip@v1
        with:
          files: ./bin/neutralino-linux_x64 ./bin/neutralino-win_x64.exe
          dest: './bin/neutralinojs-v${{github.event.inputs.version}}.zip'

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{github.event.inputs.version}}
          name: Neutralinojs experimental v${{github.event.inputs.version}}
          artifacts: './bin/neutralinojs-v${{github.event.inputs.version}}.zip'
